version: 2.1
references:
  setup_env: &setup_env
    docker:
      - image: circleci/node:14.4
  save_cache: &save_cache
    key: v2-dependency-cache-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn
      - ~/project/node_modules
      - ~/project/react-ui/node_modules
  restore_cache: &restore_cache
    keys:
      - v2-dependency-cache-{{ checksum "yarn.lock" }}
      - v2-dependency-cache-
  persist_to_workspace: &persist_to_workspace
    root: "."
    paths:
      - .
  attach_workspace: &attach_workspace
    at: "."
  # deploy_filter: &deploy_filter
  #   branches:
  #     only:
  #       - master
jobs:
  install_dependencies:
    <<: *setup_env
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: yarn --frozen-lockfile
      - save_cache: *save_cache
      - persist_to_workspace: *persist_to_workspace
  build:
    <<: *setup_env
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - run: yarn build
      - persist_to_workspace: *persist_to_workspace
  lint:
    <<: *setup_env
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - run: yarn lint:ci
  test:
    <<: *setup_env
    steps:
      - checkout
      - attach_workspace: *attach_workspace
      - run: yarn test
  # deploy:
  #   docker:
  #     - image: buildpack-deps:trusty
  #   steps:
  #     - checkout
  #     - run:
  #         name: Deploy Master to Heroku
  #         command: |
  #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
            - build
      # - deploy:
      #     requires:
      #       - install_dependencies
      #       - build
      #       - lint
      #       - test
      #     filters: *deploy_filter
